version: 2.1
jobs:
  # Download, install and cache dependencies
  Tests:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          paths:
            - project
          root: ~/
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules
      - run:
          name: run tests
          command: npm run test

workflows:
  push:
    jobs:
      - Tests