BEGIN;

    DROP TABLE IF EXISTS countries, things_to_do, businesses, experiences
    CASCADE;

CREATE TABLE countries
(
    id SERIAL PRIMARY KEY,
    country_name VARCHAR(255) NOT NULL,
    continent VARCHAR(50)
);

CREATE TABLE things_to_do

(   id SERIAL PRIMARY KEY,
    country_id INTEGER REFERENCES countries(id),
    name VARCHAR(255) NOT NULL,
    details TEXT,
    date_time TEXT,
    location TEXT,
    approved BOOL DEFAULT FALSE,
    created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE businesses
(   id SERIAL PRIMARY KEY,
    country_id INTEGER REFERENCES countries(id),
    name VARCHAR(255) NOT NULL,
    details TEXT,
    location TEXT,
    tags text[],
    approved BOOL DEFAULT FALSE,
    created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE experiences
(   id SERIAL PRIMARY KEY,
    country_id INTEGER REFERENCES countries(id),
    socials TEXT,
    details TEXT,
    tags text[],
    overall_experience TEXT,
    approved BOOL DEFAULT FALSE,
    created_at timestamp NOT NULL DEFAULT NOW()
);

        INSERT INTO countries
            (country_name, continent)
        VALUES
            ('Afghanistan','Asia'),
            ('Albania', 'Europe'),
            ('Algeria','Africa'),
            ('Andorra', 'Europe'),
            ('Angola','Africa'),
            ('Antigua and Barbuda','The Caribbean'),
            ('Argentina', 'South America'),
            ('Armenia','Asia'),
            ('Australia', 'Oceania'),
            ('Austria', 'Europe'),
            ('Azerbaijan', 'Asia'),
            ('Bahamas','The Caribbean'),
            ('Bahrain','Asia'),
            ('Bangladesh','Asia'),
            ('Barbados','The Caribbean'),
            ('Belarus','Europe'),
            ('Belgium','Europe'),
            ('Belize', 'Central America'),
            ('Benin','Africa'),
            ('Bhutan','Asia'),
            ('Bolivia', 'South America'),
            ('Bosnia and Herzegovina', 'Europe'),
            ('Botswana','Africa'),
            ('Brazil', 'South America'),
            ('Brunei','Asia'),
            ('Bulgaria','Europe'),
            ('Burkina Faso','Africa'),
            ('Burundi','Africa'),
            ('Cape Verde','Africa'),
            ('Cambodia', 'Asia'),
            ('Cameroon','Africa'),
            ('Canada', 'North America'),
            ('Central African Republic','Africa'),
            ('Chad','Africa'),
            ('Chile', 'South America'),
            ('China','Asia'),
            ('Colombia', 'South America'),
            ('Comoros','Africa'),
            ('Costa Rica', 'Central America'),
            ('Cote d''Ivoire','Africa'),
            ('Croatia','Europe'),
            ('Cuba','The Caribbean'),
            ('Cyprus','Asia'),
            ('Czech Republic','Europe'),
            ('Democratic Republic of Congo','Africa'),
            ('Denmark','Europe'),
            ('Djibouti','Africa'),
            ('Dominica','The Caribbean'),
            ('Dominican Republic','The Caribbean'),
            ('Ecuador','South America'),
            ('Egypt','Africa'),
            ('El Salvador','Central America'),
            ('Equatorial Guinea','Africa'),
            ('Eritrea','Africa'),
            ('Estonia','Europe'),
            ('Eswatini','Africa'),
            ('Ethiopia','Africa'),
            ('Fiji', 'Oceania'),
            ('Finland','Europe'),
            ('France','Europe'),
            ('Gabon','Africa'),
            ('Gambia','Africa'),
            ('Georgia','Asia'),
            ('Germany','Europe'),
            ('Ghana','Africa'),
            ('Greece','Europe'),
            ('Grenada','The Caribbean'),
            ('Guatemala', 'Central America'),
            ('Guinea','Africa'),
            ('Guinea-Bissau','Africa'),
            ('Guyana', 'South America'),
            ('Haiti','The Caribbean'),
            ('Honduras', 'Central America'),
            ('Hungary','Europe'),
            ('Iceland','Europe'),
            ('India','Asia'),
            ('Indonesia','Asia'),
            ('Iran','Asia'),
            ('Iraq','Asia'),
            ('Ireland','Europe'),
            ('Israel','Asia'),
            ('Italy','Europe'),
            ('Jamaica','The Caribbean'),
            ('Japan','Asia'),
            ('Jordan','Asia'),
            ('Kazakhstan','Asia'),
            ('Kenya','Africa'),
            ('Kiribati', 'Oceania'),
            ('Kosovo', 'Europe'),
            ('Kuwait','Asia'),
            ('Kyrgyzstan','Asia'),
            ('Laos','Asia'),
            ('Latvia','Europe'),
            ('Lebanon','Asia'),
            ('Lesotho','Africa'),
            ('Liberia','Africa'),
            ('Libya','Africa'),
            ('Liechtenstein','Europe'),
            ('Lithuania','Europe'),
            ('Luxembourg','Europe'),
            ('Madagascar','Africa'),
            ('Malawi','Africa'),
            ('Malaysia','Asia'),
            ('Maldives','Asia'),
            ('Mali','Africa'),
            ('Malta','Europe'),
            ('Marshall Islands', 'Oceania'),
            ('Mauritania','Africa'),
            ('Mauritius','Africa'),
            ('Mexico', 'North America'),
            ('Micronesia', 'Oceania'),
            ('Moldova','Europe'),
            ('Monaco','Europe'),
            ('Mongolia','Asia'),
            ('Montenegro','Europe'),
            ('Morocco','Africa'),
            ('Mozambique','Africa'),
            ('Myanmar','Asia'),
            ('Namibia','Africa'),
            ('Nauru', 'Oceania'),
            ('Nepal','Asia'),
            ('Netherlands','Europe'),
            ('New Zealand', 'Oceania'),
            ('Nicaragua', 'Central America'),
            ('Niger','Africa'),
            ('Nigeria','Africa'),
            ('North Korea','Asia'),
            ('North Macedonia', 'Europe'),
            ('Norway','Europe'),
            ('Oman','Asia'),
            ('Pakistan','Asia'),
            ('Palau', 'Oceania'),
            ('Palestine','Asia'),
            ('Panama', 'Central America'),
            ('Papua New Guinea','Oceania'),
            ('Paraguay','South America'),
            ('Peru', 'South America'),
            ('Philippines','Asia'),
            ('Poland','Europe'),
            ('Portugal','Europe'),
            ('Qatar','Asia'),
            ('Republic of the Congo','Africa'),
            ('Romania','Europe'),
            ('Russia','Asia'),
            ('Rwanda','Africa'),
            ('Saint Kitts and Nevis','The Caribbean'),
            ('Saint Lucia','The Caribbean'),
            ('Saint Vincent and the Grenadines','The Caribbean'),
            ('Samoa', 'Oceania'),
            ('San Marino','Europe'),
            ('Sao Tome and Principe','Africa'),
            ('Saudi Arabia','Asia'),
            ('Senegal','Africa'),
            ('Serbia','Europe'),
            ('Seychelles','Africa'),
            ('Sierra Leone','Africa'),
            ('Singapore','Asia'),
            ('Slovakia','Europe'),
            ('Slovenia','Europe'),
            ('Solomon Islands','Oceania'),
            ('Somalia','Africa'),
            ('South Africa','Africa'),
            ('South Korea','Asia'),
            ('South Sudan','Africa'),
            ('Spain','Europe'),
            ('Sri Lanka','Asia'),
            ('Sudan','Africa'),
            ('Suriname','South America'),
            ('Sweden','Europe'),
            ('Switzerland','Europe'),
            ('Syria','Asia'),
            ('Taiwan','Asia'),
            ('Tajikistan','Asia'),
            ('Tanzania','Africa'),
            ('Thailand','Asia'),
            ('Timor-Leste','Asia'),
            ('Togo','Africa'),
            ('Tonga', 'Oceania'),
            ('Trinidad and Tobago','The Caribbean'),
            ('Tunisia','Africa'),
            ('Turkey','Asia'),
            ('Turkmenistan','Asia'),
            ('Tuvalu', 'Oceania'),
            ('Uganda','Africa'),
            ('Ukraine','Europe'),
            ('United Arab Emirates','Asia'),
            ('United Kingdom','Europe'),
            ('United States of America','North America'),
            ('Uruguay','South America'),
            ('Uzbekistan','Asia'),
            ('Vanuatu','Oceania'),
            ('Vatican City', 'Europe'),
            ('Venezuela','South America'),
            ('Vietnam','Asia'),
            ('Yemen','Asia'),
            ('Zambia','Africa'),
            ('Zimbabwe','Africa');


COMMIT;

INSERT INTO experiences (country_id, socials, details, tags, overall_experience, approved) VALUES
    (7, 'social stuff idk', 'Food was amazing!', '{"black", "queer"}', 'Good', TRUE),
    (52, 'instagram.com/yolo', 'Troll review', '{"black", "trans"}', 'Bad', FALSE);


INSERT INTO things_to_do (country_id, name, details, date_time,location, approved) VALUES
    (7, 'Bobby', 'Great view!','date and time string from new Date()', 'Buenos Aires', TRUE),
    (77, 'Pride Festival', 'The biggest celebration of queer culture', '6 September', 'Paris', TRUE),
    (120, 'Hateful content', 'rubbish rubbish', 'never', 'Nowhere', FALSE),
    (30, 'More poop content', 'crazy shit', '5th sept', 'The beach', FALSE);


INSERT INTO businesses (country_id, name, details, location, tags, approved) VALUES
    (150, 'Tarek''s Tacos', 'Fantastic service at a great price.','Downtown', '{"black"}', TRUE);








COMMIT;

